//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsdl.FreshTrade.UI.PreInv.PreInvReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PreInvReportService.IPreInvReportService", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IPreInvReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreInvReportService/GenerateReport", ReplyAction="http://tempuri.org/IPreInvReportService/GenerateReportResponse")]
        System.Data.DataTable[] GenerateReport(string reportName, System.Collections.Generic.Dictionary<string, string> reportParams);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPreInvReportServiceChannel : Bsdl.FreshTrade.UI.PreInv.PreInvReportService.IPreInvReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PreInvReportServiceClient : System.ServiceModel.ClientBase<Bsdl.FreshTrade.UI.PreInv.PreInvReportService.IPreInvReportService>, Bsdl.FreshTrade.UI.PreInv.PreInvReportService.IPreInvReportService {
        
        public PreInvReportServiceClient() {
        }
        
        public PreInvReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PreInvReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreInvReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreInvReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable[] GenerateReport(string reportName, System.Collections.Generic.Dictionary<string, string> reportParams) {
            return base.Channel.GenerateReport(reportName, reportParams);
        }
    }
}
