//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsdl.FreshTrade.UI.PreInv.SalesOfficeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalesOfficeService.ISalesOfficesService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ISalesOfficesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalesOfficesService/GetSalesOffices", ReplyAction="http://tempuri.org/ISalesOfficesService/GetSalesOfficesResponse")]
        Bsdl.FreshTrade.Domain.Account.Entities.DTOSalesOffice[] GetSalesOffices();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalesOfficesServiceChannel : Bsdl.FreshTrade.UI.PreInv.SalesOfficeService.ISalesOfficesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesOfficesServiceClient : System.ServiceModel.ClientBase<Bsdl.FreshTrade.UI.PreInv.SalesOfficeService.ISalesOfficesService>, Bsdl.FreshTrade.UI.PreInv.SalesOfficeService.ISalesOfficesService {
        
        public SalesOfficesServiceClient() {
        }
        
        public SalesOfficesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesOfficesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesOfficesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesOfficesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bsdl.FreshTrade.Domain.Account.Entities.DTOSalesOffice[] GetSalesOffices() {
            return base.Channel.GetSalesOffices();
        }
    }
}
