create or replace PACKAGE FT_AUTOCOSTING AS
...
  
  TYPE T_INTEGER_ARRAY IS TABLE OF INTEGER INDEX BY PLS_INTEGER;
  PROCEDURE ENQUEUE_DPRRECS_AA(DPRRECS_IN T_INTEGER_ARRAY, COSTCHNGTYPE_IN AUTOCOSTTYPES.COSTCHNGTYPENO%TYPE);  
END FT_AUTOCOSTING;

...

create or replace PACKAGE BODY FT_AUTOCOSTING AS
...

  PROCEDURE ENQUEUE_DPRRECS_AA(
      DPRRECS_IN T_INTEGER_ARRAY,
      COSTCHNGTYPE_IN AUTOCOSTTYPES.COSTCHNGTYPENO%TYPE)
  AS
     DelPriceIds RECORD_NUMBERS := RECORD_NUMBERS();
  BEGIN
      for i in DPRRECS_IN.first..DPRRECS_IN.last
      LOOP
        DelPriceIds.EXTEND;
        DelPriceIds(i) := DPRRECS_IN(i);
      END LOOP;
    FT_AUTOCOSTING.ENQUEUE_DPRRECS(DelPriceIds, COSTCHNGTYPE_IN);
    RETURN;
  END ENQUEUE_DPRRECS_AA;

END FT_AUTOCOSTING;