//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsdl.FreshTrade.UI.PreInv.PreInvService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PreInvService.IPreInvService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IPreInvService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreInvService/Extract", ReplyAction="http://tempuri.org/IPreInvService/ExtractResponse")]
        Bsdl.FreshTrade.Domain.PreInv.Entities.DTOPreInvExtractResult Extract(Bsdl.FreshTrade.Domain.PreInv.Entities.DTOPreInvExtractParams extractParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreInvService/GetProgress", ReplyAction="http://tempuri.org/IPreInvService/GetProgressResponse")]
        System.Nullable<int> GetProgress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreInvService/PrepareForPrint", ReplyAction="http://tempuri.org/IPreInvService/PrepareForPrintResponse")]
        System.Collections.Generic.Dictionary<string, string> PrepareForPrint(Bsdl.FreshTrade.Domain.PreInv.Entities.DTOPreInvUpdateParams updateParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreInvService/Update", ReplyAction="http://tempuri.org/IPreInvService/UpdateResponse")]
        Bsdl.FreshTrade.Domain.PreInv.Enums.PreInvUpdateStatusType Update(Bsdl.FreshTrade.Domain.PreInv.Entities.DTOPreInvUpdateParams updateParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreInvService/CleanUp", ReplyAction="http://tempuri.org/IPreInvService/CleanUpResponse")]
        void CleanUp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPreInvService/GetExportData", ReplyAction="http://tempuri.org/IPreInvService/GetExportDataResponse")]
        string GetExportData(Bsdl.FreshTrade.Domain.PreInv.Entities.DTOPreInvUpdateParams updateParams);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPreInvServiceChannel : Bsdl.FreshTrade.UI.PreInv.PreInvService.IPreInvService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PreInvServiceClient : System.ServiceModel.ClientBase<Bsdl.FreshTrade.UI.PreInv.PreInvService.IPreInvService>, Bsdl.FreshTrade.UI.PreInv.PreInvService.IPreInvService {
        
        public PreInvServiceClient() {
        }
        
        public PreInvServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PreInvServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreInvServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreInvServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bsdl.FreshTrade.Domain.PreInv.Entities.DTOPreInvExtractResult Extract(Bsdl.FreshTrade.Domain.PreInv.Entities.DTOPreInvExtractParams extractParams) {
            return base.Channel.Extract(extractParams);
        }
        
        public System.Nullable<int> GetProgress() {
            return base.Channel.GetProgress();
        }
        
        public System.Collections.Generic.Dictionary<string, string> PrepareForPrint(Bsdl.FreshTrade.Domain.PreInv.Entities.DTOPreInvUpdateParams updateParams) {
            return base.Channel.PrepareForPrint(updateParams);
        }
        
        public Bsdl.FreshTrade.Domain.PreInv.Enums.PreInvUpdateStatusType Update(Bsdl.FreshTrade.Domain.PreInv.Entities.DTOPreInvUpdateParams updateParams) {
            return base.Channel.Update(updateParams);
        }
        
        public void CleanUp() {
            base.Channel.CleanUp();
        }
        
        public string GetExportData(Bsdl.FreshTrade.Domain.PreInv.Entities.DTOPreInvUpdateParams updateParams) {
            return base.Channel.GetExportData(updateParams);
        }
    }
}
