using System.Text;
using Bsdl.FreshTrade.Domain.PreInv.Entities;
using Bsdl.FreshTrade.Repositories.Basic.Utilities.Interfaces;
using Bsdl.FreshTrade.Repositories.PreInv.Interfaces;

namespace Bsdl.FreshTrade.Services.PreInv.Model
{
    public static class StringExt
    {
        public static string Quote(this string text)
        {
            return text == null
                ? null
                : "\"" + text.Trim().Replace("\"", "\"\"") + "\"";
        }

    }

    public class DataExportProcessor
    {
        private readonly IInvPrt2Repository _preInvPrt2Repository;


        public DataExportProcessor(IUnitOfWork unitOfWorkCurrent)
        {
            _preInvPrt2Repository = unitOfWorkCurrent.GetRepository<IInvPrt2Repository>();
        }


        public string Process(DTOPreInvUpdateParams preparePrintParams, int extractSessionId)
        {
            var preInvPart2 = _preInvPrt2Repository.GetInvPrt2ByExtractionSessionId(extractSessionId, preparePrintParams.SelectedPreInvPrt2);
            var exporter = new StringBuilder();

            // build file header
            exporter.Append("InvoiceNo");
            exporter.Append(",");
            exporter.Append("Recno");
            exporter.Append(",");
            exporter.Append("DlvOrdNo");
            exporter.Append(",");
            exporter.Append("DelRecNo");
            exporter.Append(",");
            exporter.Append("PpcNo");
            exporter.Append(",");
            exporter.Append("DelQty");
            exporter.Append(",");
            exporter.Append("DelWeight");
            exporter.Append(",");
            exporter.Append("DelPrice");
            exporter.Append(",");
            exporter.Append("Goods");
            exporter.Append(",");
            exporter.Append("Vat");
            exporter.Append(",");
            exporter.Append("Ext");
            exporter.Append(",");
            exporter.Append("VatVatRate");
            exporter.Append(",");
            exporter.Append("OnInvDscnt");
            exporter.Append(",");
            exporter.Append("OnInvDisPcnt");
            exporter.Append(",");
            exporter.Append("Dispcnt");
            exporter.Append(",");
            exporter.Append("OffInvRbt");
            exporter.Append(",");
            exporter.Append("OffInvOnPay");
            exporter.Append(",");
            exporter.Append("DprRecNo");
            exporter.Append(",");
            exporter.Append("DelCdsRefNo");
            exporter.Append(",");
            exporter.Append("VatRecNo");
            exporter.Append(",");
            exporter.Append("EuroGds");
            exporter.Append(",");
            exporter.Append("EuroVat");
            exporter.Append(",");
            exporter.Append("EuroOnInvDscnt");
            exporter.Append(",");
            exporter.Append("EuroOffInvRbt");
            exporter.Append(",");
            exporter.Append("EuroOffOnPay");
            exporter.Append(",");
            exporter.Append("BaseVat");
            exporter.Append(",");
            exporter.Append("BaseGds");
            exporter.Append(",");
            exporter.Append("BaseOnInvDscnt");
            exporter.Append(",");
            exporter.Append("BaseOffInvRbt");
            exporter.Append(",");
            exporter.Append("BaseOffOnPay");
            exporter.Append(",");
            exporter.Append("AllocToInvRecNo");
            exporter.Append(",");
            exporter.Append("DetAllocNo");
            exporter.Append(",");
            exporter.Append("PrcPrdRef");
            exporter.Append(",");
            exporter.Append("PrdRecDesc");
            exporter.Append(",");
            exporter.Append("Handrate");
            exporter.Append(",");
            exporter.Append("Commperc");
            exporter.Append(",");
            exporter.Append("Rawhandamt");
            exporter.Append(",");
            exporter.Append("Rawcommamt");
            exporter.Append(",");
            exporter.Append("Rawvatonchgs");
            exporter.Append(",");
            exporter.Append("Vatcodechgs");
            exporter.Append(",");
            exporter.Append("Vatratechgs");
            exporter.Append(",");
            exporter.Append("Basehandamt");
            exporter.Append(",");
            exporter.Append("Basecommamt");
            exporter.Append(",");
            exporter.Append("Basevatonchgs");
            exporter.Append(",");
            exporter.Append("Eurohandamt");
            exporter.Append(",");
            exporter.Append("Eurocommamt");
            exporter.Append(",");
            exporter.Append("Eurovatonchgs");
            exporter.Append(",");
            exporter.Append("VatVeaRecNo");
            exporter.Append(",");
            exporter.Append("PrgRefNo");
            exporter.Append(",");
            exporter.Append("PrdGlAnl");
            exporter.Append(",");
            exporter.Append("DelCltPrdNo");
            exporter.Append(",");
            exporter.Append("DelPrcPrdNo");
            exporter.Append(",");
            exporter.Append("PrdDesc");
            exporter.Append(",");
            exporter.Append("TradedUnit");
            exporter.Append(",");
            exporter.Append("UnitCount");
            exporter.Append(",");
            exporter.Append("PrtQty");
            exporter.Append(",");
            exporter.Append("DelPrcByWgt");
            exporter.Append(",");
            exporter.Append("DelInvStatus");
            exporter.Append(",");
            exporter.Append("AllowOneLineCancel");
            exporter.Append(",");
            exporter.Append("CancelledLine");
            exporter.Append(",");
            exporter.Append("VatLnkRecNo");
            exporter.Append(",");
            exporter.Append("VatVatRate2");
            exporter.Append(",");
            exporter.Append("Vat1Total");
            exporter.Append(",");
            exporter.Append("Vat2Total");
            exporter.Append(",");
            exporter.Append("EuroVat1Total");
            exporter.Append(",");
            exporter.Append("EuroVat2Total");
            exporter.Append(",");
            exporter.Append("BaseVat1Total");
            exporter.Append(",");
            exporter.Append("BaseVat2Total");
            exporter.Append(",");
            exporter.Append("UnitMeasure");
            exporter.Append(",");
            exporter.Append("DiscToQty");
            exporter.Append(",");
            exporter.Append("GrossWgt");
            exporter.Append(",");
            exporter.Append("TareWgt");
            exporter.Append(",");
            exporter.Append("NettWgt");
            
            exporter.Append(",");
            exporter.AppendLine();
            // load data
            foreach (var dtoInvPrt2 in preInvPart2)
            {
                exporter.Append("");
                exporter.Append(dtoInvPrt2.InvoiceNo.Quote());
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Recno);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DlvOrdNo);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DelRecNo);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.PpcNo);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DelQty);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DelWeight);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DelPrice);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Goods);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Vat);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Ext);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.VatVatRate);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.OnInvDscnt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.OnInvDisPcnt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Dispcnt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.OffInvRbt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.OffInvOnPay);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DprRecNo);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DelCdsRefNo);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.VatRecNo);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.EuroGds);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.EuroVat);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.EuroOnInvDscnt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.EuroOffInvRbt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.EuroOffOnPay);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.BaseVat);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.BaseGds);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.BaseOnInvDscnt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.BaseOffInvRbt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.BaseOffOnPay);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.AllocToInvRecNo);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DetAllocNo.Quote());
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.PrcPrdRef.Quote());
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.PrdRecDesc.Quote());
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Handrate);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Commperc);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Rawhandamt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Rawcommamt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Rawvatonchgs);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Vatcodechgs);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Vatratechgs);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Basehandamt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Basecommamt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Basevatonchgs);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Eurohandamt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Eurocommamt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Eurovatonchgs);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.VatVeaRecNo);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.PrgRefNo);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.PrdGlAnl);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DelCltPrdNo.Quote());
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DelPrcPrdNo);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.PrdDesc.Quote());
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.TradedUnit.Quote());
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.UnitCount);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.PrtQty);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DelPrcByWgt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DelInvStatus);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.AllowOneLineCancel);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.CancelledLine);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.VatLnkRecNo);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.VatVatRate2);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Vat1Total);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.Vat2Total);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.EuroVat1Total);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.EuroVat2Total);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.BaseVat1Total);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.BaseVat2Total);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.UnitMeasure.Quote());
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.DiscToQty);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.GrossWgt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.TareWgt);
                exporter.Append(",");
                exporter.Append(dtoInvPrt2.NettWgt);
                exporter.Append(",");
                exporter.AppendLine();
            }
            return exporter.ToString();
        }
    }
}
