DELETE FROM "PREINVTEMP_INVPRT"; 
DELETE FROM "PREINVTEMP_PREINVPRT";

ALTER TABLE "PREINVTEMP_INVPRT" 
ADD "RECNO" NUMBER(10,0) NOT NULL ENABLE;
ALTER TABLE "PREINVTEMP_PREINVPRT" 
ADD "RECNO" NUMBER(10,0) NOT NULL ENABLE;
COMMIT
