ALTER TABLE "PREINVTEMP_INVPRT" 
ADD "RECNO" NUMBER(10,0);
ALTER TABLE "PREINVTEMP_PREINVPRT" 
ADD "RECNO" NUMBER(10,0);
COMMIT
ALTER TABLE "PREINVTEMP_INVPRT2" 
ADD "INVPRTRECNO" NUMBER(10,0);
ALTER TABLE "PREINVTEMP_PREINVPRT2" 
ADD "INVPRTRECNO" NUMBER(10,0);
COMMIT
