CREATE TABLE DELAUDIT_INT 
   (      
 DELAUDINTRECNO NUMBER(10) NOT NULL , 
 DELAUDINTDELRECNO NUMBER(10), 
  DELAUDINTTYP NUMBER(5), 
  DELAUDINTGRPNO NUMBER(10), 
  DELAUDINTDATE DATE,  
  DELAUDINTFROM VARCHAR2(255), 
  DELAUDINTTO VARCHAR2(255), 
  FORMINTNO NUMBER(5), 
  LOGONINTNO NUMBER(5), 
  DPRRECNOINT NUMBER(10), 
    CONSTRAINT "PK_DELAUDINTRECNO" PRIMARY KEY (DELAUDINTRECNO)
   ); 


CREATE SEQUENCE DELAUDIT_INT_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCYCLE CACHE 20 NOORDER;

