DROP TABLE  PREINVTEMP_InvErr;
CREATE TABLE  PREINVTEMP_InvErr(  
  ExtractSessionID NUMBER(10,0)  NOT NULL ENABLE,
  LogRecNo NUMBER(10,0) NOT NULL ENABLE,
  ErrNo NUMBER(10,0) NOT NULL ENABLE,
  OrdCstCode VARCHAR(8),
  OrdCustOrdNo VARCHAR(25),
  DlvOrdNo NUMBER(10,0)
);
