DROP TABLE PREINVTEMP_InvExtractHed;
CREATE TABLE PREINVTEMP_InvExtractHed
(  
  ExtractSessionID NUMBER(10,0) NOT NULL ENABLE, 
  LogonNo NUMBER(5,0) NOT NULL ENABLE,
  SalesOfficeNo NUMBER(5,0) NOT NULL ENABLE,
  SalesOfficeName VARCHAR(50) NOT NULL ENABLE,
  InvoiceType NUMBER(5,0) NOT NULL ENABLE,
  InvoiceTypeName VARCHAR(50) NOT NULL ENABLE,
  CreatedDate DATE NOT NULL ENABLE,
  ReqDate DATE NOT NULL ENABLE,
  TaxDate DATE NOT NULL ENABLE,
  InvoicePeriod NUMBER(5,0) NOT NULL ENABLE,
  InvoicePeriodAsStr VARCHAR(50) NOT NULL ENABLE,
  InvoiceOrderType VARCHAR(50) NOT NULL ENABLE,
  IsInterCompanyTransfer NUMBER(1, 0) NOT NULL ENABLE,
  CompanyNo NUMBER(10,0) NOT NULL ENABLE,
  LastInvoiceNo NUMBER(10,0) NOT NULL ENABLE,
  CONSTRAINT "PK_PREINVTEMP_InvExtractHed" PRIMARY KEY (ExtractSessionID) ENABLE
);