DROP TABLE  PREINVTEMP_InvPrt;
CREATE TABLE  PREINVTEMP_InvPrt(
  ExtractSessionID NUMBER(10,0)  NOT NULL ENABLE,
  DlvInvoiceNo VARCHAR(20),
  DlvOrdNo NUMBER(10,0),
  DlvShpDate DATE,
  DlvDelDate DATE,
  DlvPODNo VARCHAR(15),
  OrdRecNo NUMBER(10,0),
  OrdCstCode VARCHAR(8),
  OrdCustOrdNo VARCHAR(25),
  OrdDate DATE,
  OrdSmnNo NUMBER(10,0),
  HofCstCode VARCHAR(8),
  InvoiceType NUMBER(10,0),
  PrcGlbRecNo NUMBER(10,0),
  IsEdiPrg NUMBER(1,0),
  CurDesc VARCHAR(30),
  Sort1 VARCHAR(30),
  Sort2 VARCHAR(30),
  Invdate DATE,
  HofClaRecNo NUMBER(10,0),
  DelClaRecNo NUMBER(10,0),
  DltRecNo NUMBER(10,0),
  DlvPrgHedNo NUMBER(10,0),
  CancelledDlv NUMBER(10,0),
  Vatable VARCHAR(1),
  DlvSalOffNo NUMBER(10,0),
  SalOffDesc VARCHAR(23)
);
