  CREATE TABLE "PREINVTEMP_PREINVDISCTYP" 
   (	"EXTRACTSESSIONID" NUMBER(10,0) NOT NULL ENABLE, 
	"DLVINVOICENO" VARCHAR2(20 BYTE), 
	"RECNO" NUMBER(10,0), 
	"DISCSEQNO" NUMBER(10,0), 
	"DISCTYP" NUMBER(10,0), 
	"DISCRATE" FLOAT(126), 
	"DISCDETRSTR" VARCHAR2(30 BYTE), 
	"DISCBASEAMT" FLOAT(126), 
	"DISCLOCLAMT" FLOAT(126), 
	"DISCEUROAMT" FLOAT(126), 
	"DISCGLRECNO" NUMBER(10,0), 
	"ICHRECNO" NUMBER(10,0)
   ) ;