  CREATE GLOBAL TEMPORARY TABLE PREINVTEMP_EXTRACTSTOCLEANUP 
  (
    EXTRACTSESSIONID NUMBER(10, 0) NOT NULL PRIMARY KEY
  ) ON COMMIT DELETE ROWS;
CREATE OR REPLACE PROCEDURE CLEARPREINVTEMPDATA2 AS 
BEGIN

  INSERT INTO PREINVTEMP_EXTRACTSTOCLEANUP
  SELECT E.EXTRACTSESSIONID
  FROM PREINVTEMP_INVEXTRACTHED E 
    LEFT JOIN SALOFFNO S ON S.SALOFFNO = E.SALESOFFICENO AND S.INUSE = 1
  WHERE S.SALOFFNO IS NULL;

  DELETE FROM
  (
    SELECT D.EXTRACTSESSIONID
    FROM PREINVTEMP_PREINVDISCTYP D
      INNER JOIN PREINVTEMP_EXTRACTSTOCLEANUP E ON E.EXTRACTSESSIONID = D.EXTRACTSESSIONID
  );

  DELETE FROM
  (
    SELECT D.EXTRACTSESSIONID
    FROM PREINVTEMP_PREINVPRT D
      INNER JOIN PREINVTEMP_EXTRACTSTOCLEANUP E ON E.EXTRACTSESSIONID = D.EXTRACTSESSIONID
  );

  DELETE FROM
  (
    SELECT D.EXTRACTSESSIONID
    FROM PREINVTEMP_PREINVPRT2 D
      INNER JOIN PREINVTEMP_EXTRACTSTOCLEANUP E ON E.EXTRACTSESSIONID = D.EXTRACTSESSIONID
  );

  DELETE FROM
  (
    SELECT D.EXTRACTSESSIONID
    FROM PREINVTEMP_PREINVTOT D
      INNER JOIN PREINVTEMP_EXTRACTSTOCLEANUP E ON E.EXTRACTSESSIONID = D.EXTRACTSESSIONID
  );


  DELETE FROM
  (
    SELECT D.EXTRACTSESSIONID
    FROM PREINVTEMP_INVPRT2 D
      INNER JOIN PREINVTEMP_EXTRACTSTOCLEANUP E ON E.EXTRACTSESSIONID = D.EXTRACTSESSIONID
  );

  DELETE FROM
  (
    SELECT D.EXTRACTSESSIONID
    FROM PREINVTEMP_INVPRT D
      INNER JOIN PREINVTEMP_EXTRACTSTOCLEANUP E ON E.EXTRACTSESSIONID = D.EXTRACTSESSIONID
  );

  DELETE FROM
  (
    SELECT D.EXTRACTSESSIONID
    FROM PREINVTEMP_INVTOT D
      INNER JOIN PREINVTEMP_EXTRACTSTOCLEANUP E ON E.EXTRACTSESSIONID = D.EXTRACTSESSIONID
  );

  DELETE FROM
  (
    SELECT D.EXTRACTSESSIONID
    FROM PREINVTEMP_INVERR D
      INNER JOIN PREINVTEMP_EXTRACTSTOCLEANUP E ON E.EXTRACTSESSIONID = D.EXTRACTSESSIONID
  );

  DELETE FROM
  (
    SELECT D.EXTRACTSESSIONID
    FROM PREINVTEMP_INVEDI D
      INNER JOIN PREINVTEMP_EXTRACTSTOCLEANUP E ON E.EXTRACTSESSIONID = D.EXTRACTSESSIONID
  );

  DELETE FROM
  (
    SELECT D.EXTRACTSESSIONID
    FROM PREINVTEMP_INVDISCTYP D
      INNER JOIN PREINVTEMP_EXTRACTSTOCLEANUP E ON E.EXTRACTSESSIONID = D.EXTRACTSESSIONID
  );

  DELETE FROM 
  (
    SELECT D.SALESOFFICENO
    FROM PREINVTEMP_INVEXTRACTHED D
      INNER JOIN PREINVTEMP_EXTRACTSTOCLEANUP E ON E.EXTRACTSESSIONID = D.EXTRACTSESSIONID
  );

END CLEARPREINVTEMPDATA2;