ALTER TABLE "DELPRICE" 
ADD "DPRCDTREFNO_TEMP" NUMBER(10,0);

UPDATE "DELPRICE" 
SET DPRCDTREFNO_TEMP = CAST(DPRCDTREFNO as NUMBER(10, 0))
WHERE DPRCDTREFNO IS NOT NULL;

ALTER TABLE "DELPRICE" 
DROP COLUMN DPRCDTREFNO;

ALTER TABLE "DELPRICE" 
ADD "DPRCDTREFNO" NUMBER(10,0);

UPDATE "DELPRICE" 
SET DPRCDTREFNO = DPRCDTREFNO_TEMP
WHERE DPRCDTREFNO_TEMP IS NOT NULL;

ALTER TABLE "DELPRICE" 
DROP COLUMN DPRCDTREFNO_TEMP;

COMMENT ON COLUMN "DELPRICE"."DPRCDTREFNO" IS 'The credit reference. Foreign Key - DELPRICE_CREDITREF';

CREATE INDEX "DELPRICE_DPRCDTREFNO" ON "DELPRICE" ("DPRCDTREFNO") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);




CREATE TABLE "DELPRICE_CREDITREF_TEMP" 
 (  "DPRCDTREFNO" NUMBER(10,0) NOT NULL ENABLE, 
"CREDITREF" CHAR(20 BYTE), 
"DLVORDNO" NUMBER(10,0) NOT NULL ENABLE, 
"INVSTATUS" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE, 
 CONSTRAINT "DELPRICE_CREDITREF_TEMP_PK" PRIMARY KEY ("DPRCDTREFNO")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
ENABLE
 ) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

INSERT INTO DELPRICE_CREDITREF_TEMP
(
"DPRCDTREFNO", 
"CREDITREF", 
"DLVORDNO", 
"INVSTATUS"
)
SELECT 
"DPRCDTREFNO", 
"CREDITREF", 
"DLVORDNO", 
"INVSTATUS"
FROM DELPRICE_CREDITREF;

DROP TABLE DELPRICE_CREDITREF;


CREATE TABLE "DELPRICE_CREDITREF" 
 (  "DPRCDTREFNO" NUMBER(10,0) NOT NULL ENABLE, 
"CREDITREF" CHAR(20 BYTE), 
"DLVORDNO" NUMBER(10,0) NOT NULL ENABLE, 
"INVSTATUS" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE, 
 CONSTRAINT "DELPRICE_CREDITREF_PK" PRIMARY KEY ("DPRCDTREFNO")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
ENABLE
 ) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;


 COMMENT ON COLUMN "DELPRICE_CREDITREF"."DPRCDTREFNO" IS 'Primary Key';

 COMMENT ON COLUMN "DELPRICE_CREDITREF"."CREDITREF" IS 'Reference for this group of credit / debit lines';

 COMMENT ON COLUMN "DELPRICE_CREDITREF"."DLVORDNO" IS 'Foreign Key - DELHED.DLVORDNO';

 COMMENT ON COLUMN "DELPRICE_CREDITREF"."INVSTATUS" IS 'Status indicator. 1 = open, 10 = invoiced';

 COMMENT ON TABLE "DELPRICE_CREDITREF"  IS 'Table to group credit / debit note DELPRICEs into group for transaction generation';


CREATE INDEX "DELPRICE_CREDITREF_DLVREF" ON "DELPRICE_CREDITREF" ("DLVORDNO", "CREDITREF") 
PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

INSERT INTO DELPRICE_CREDITREF
(
"DPRCDTREFNO", 
"CREDITREF", 
"DLVORDNO", 
"INVSTATUS"
)
SELECT 
"DPRCDTREFNO", 
"CREDITREF", 
"DLVORDNO", 
"INVSTATUS"
FROM DELPRICE_CREDITREF_TEMP;

DROP TABLE DELPRICE_CREDITREF_TEMP;
