//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsdl.FreshTrade.UI.PreInv.CustomerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.ICustomerService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerGroups", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerGroupsResponse")]
        System.Collections.Generic.List<Bsdl.FreshTrade.Domain.Account.Entities.DTOCustomerGroup> GetCustomerGroups(bool isCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerCategoriesByGroup", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerCategoriesByGroupResponse")]
        System.Collections.Generic.List<Bsdl.FreshTrade.Domain.Account.Entities.DTOCustomerCategory> GetCustomerCategoriesByGroup(int custGroupId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : Bsdl.FreshTrade.UI.PreInv.CustomerService.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<Bsdl.FreshTrade.UI.PreInv.CustomerService.ICustomerService>, Bsdl.FreshTrade.UI.PreInv.CustomerService.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Bsdl.FreshTrade.Domain.Account.Entities.DTOCustomerGroup> GetCustomerGroups(bool isCustomer) {
            return base.Channel.GetCustomerGroups(isCustomer);
        }
        
        public System.Collections.Generic.List<Bsdl.FreshTrade.Domain.Account.Entities.DTOCustomerCategory> GetCustomerCategoriesByGroup(int custGroupId) {
            return base.Channel.GetCustomerCategoriesByGroup(custGroupId);
        }
    }
}
