//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bsdl.FreshTrade.UI.PreInv.AccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountService.IAccountsService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAccountsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountsService/GetAccountsBySalesOffice", ReplyAction="http://tempuri.org/IAccountsService/GetAccountsBySalesOfficeResponse")]
        Bsdl.FreshTrade.Domain.PreInv.WideObjects.WideAccountInfo[] GetAccountsBySalesOffice(int salesOfficeNo, System.Nullable<Bsdl.FreshTrade.Domain.Account.Enums.DTOAccountType> accountType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountsServiceChannel : Bsdl.FreshTrade.UI.PreInv.AccountService.IAccountsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountsServiceClient : System.ServiceModel.ClientBase<Bsdl.FreshTrade.UI.PreInv.AccountService.IAccountsService>, Bsdl.FreshTrade.UI.PreInv.AccountService.IAccountsService {
        
        public AccountsServiceClient() {
        }
        
        public AccountsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bsdl.FreshTrade.Domain.PreInv.WideObjects.WideAccountInfo[] GetAccountsBySalesOffice(int salesOfficeNo, System.Nullable<Bsdl.FreshTrade.Domain.Account.Enums.DTOAccountType> accountType) {
            return base.Channel.GetAccountsBySalesOffice(salesOfficeNo, accountType);
        }
    }
}
